services:
  - type: web
    name: video-downloader-backend
    env: node
    buildCommand: |
      corepack enable
      corepack prepare yarn@4.9.0 --activate
      yarn config set nodeLinker node-modules
      yarn --version
      yarn install --frozen-lockfile
      yarn build
      apt-get update && apt-get install -y python3 python3-pip
      pip3 install yt-dlp
    startCommand: yarn start
    envVars:
      - key: PORT
        value: 10000
    disk:
      name: downloads
      mountPath: /opt/render/project/src/public/downloads
      sizeGB: 10
